name: Unit tests

on: [push]

jobs:
  unit-test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U -r requirements.txt
          pip install -U -r tests_requirements.txt
          pip install -U coverage parameterized
      - name: Launch python tests
        run: |
          coverage run --source=flask_inertia -m unittest tests.python.test_app
          coverage report -m --fail-under=90

  unit-test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          npm install
          python -m pip install -U pip setuptools
          pip install -U -r requirements.txt
      - name: Setup tests
        run: |
          python3 setup.py install
          python3 tests/js/setup.py
      - name: Launch JS tests
        run: npm run test
